package com.example.team31_personalbest_ms2v2;

import android.graphics.Color;
import android.util.Log;

import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.components.AxisBase;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.formatter.IAxisValueFormatter;
import com.github.mikephil.charting.formatter.IndexAxisValueFormatter;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import static com.example.team31_personalbest_ms2v2.Constants.*;

/**
 * class that creates a stylized barchart
 */
public class ProgressChart implements IDataRetrieverObserver{

    BarChart bc;
    String[] bottomAxisLabels;
    List<Integer> planned;
    List<Integer> unplanned;
    List<Integer> goals;
    int len;

    /**
     * ctor that sets the class variables appropriately
     *
     * @param bc BarChart object is taken from the activity and created
     * @param unplanned list of preformatted unplanned step values
     * @param planned list of preformatted planned step values
     * @param bottomAxisLabels list of axis labels that correspond to unplanned and planned
     */
    public ProgressChart(BarChart bc, List<Integer> unplanned, List<Integer> planned,
                         List<Integer> goals, int len,
                         String[] bottomAxisLabels) {
        this.bc = bc;
        this.bottomAxisLabels = bottomAxisLabels;
        this.planned = planned;
        this.unplanned = unplanned;
        this.goals = goals;
        this.len = len;
    }

    /**
     * sets up the bar chart
     */
    public void setup() {

        // getting the axes of the graph
        XAxis bottomAxis = bc.getXAxis();
        YAxis leftAxis = bc.getAxisLeft();

        // stylizing axes
        formatAxes(bottomAxis, leftAxis);

        // creating a dataSet compatibale with barChart
        BarData data = createData();

        bc.getDescription().setEnabled(false);
        bc.setData(data);

        bc.invalidate(); // refresh
    }

    /**
     *
     */
    private void update(String label, List<String> dates, List<Integer> list) {
        Log.i("SHIT", "Updating for " + label);
        String[] dateLabels = new String[dates.size() + 1];
        this.len = dates.size();
        this.bottomAxisLabels = dates.toArray(dateLabels);
        if(label.equals("ups")) {
            unplanned = list;
        } else if(label.equals("ps")) {
            planned = list;
        } else if(label.equals("goals")) {
            goals = list;
        } else {
            return;
        }
        setup();
    }

    /**
     *
     * @param bottomAxis
     * @param leftAxis
     */
    private void formatAxes(XAxis bottomAxis, YAxis leftAxis) {

        // bottomAxis formatting ----
        // labels bars as per bottomAxisLabels
        bottomAxis.setValueFormatter(new DateFormatter());
        bottomAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        bottomAxis.setDrawLabels(true);
        bottomAxis.setDrawGridLines(false);
        bottomAxis.setDrawAxisLine(true);

        // setting the min and max of the bottom axis so that it is easy to read
        bottomAxis.setAxisMinimum(-1);
        bottomAxis.setAxisMaximum(bottomAxisLabels.length);

        // leftAxis formatting ----
        leftAxis.setDrawGridLines(false);
        // setting the minimum so irrelevant part of graph isn't shown
        leftAxis.setAxisMinimum(0);
        // we are only utilizing one axis and it will be the left one
        bc.getAxisRight().setEnabled(false);

        //bc.setVisibleXRangeMaximum(len);
    }

    /**
     *
     * @return BarData object generated by given data from ctor
     */
    private BarData createData() {
        List<BarEntry> barEntries = new ArrayList<>();

        // populating barEntries with values from planned and unplanned
        for(int i = len-1; i >= 0; i--) {
            // for the i'th elemnt to exist, goals size needs to be
            // i+1 elements atleast, so if it isn't then make the value 0
            int tmpGoal = (goals.size()<i+1) ? 0 : goals.get(i);
            int tmpUPS = (unplanned.size()<i+1) ? 0 : unplanned.get(i);
            int tmpPS = (planned.size()<i+1) ? 0 : planned.get(i);

            Log.i("SHIT", "Bar Chart is adding " + tmpUPS + " unplanned steps, " +
                    tmpPS + " planned steps, for the date of " + bottomAxisLabels[i]);

            int stepsToReachGoal = (tmpGoal-tmpUPS-tmpPS>=0) ?
                    tmpGoal-tmpUPS-tmpPS : 0;
            barEntries.add(0, new BarEntry(i, new float[]{tmpPS, tmpUPS,
                                                       stepsToReachGoal}));
        }

        // making dataset from set labeled "steps"
        BarDataSet set = new BarDataSet(barEntries, "Steps");
        // labels for the chart legend
        set.setStackLabels(new String[]{PLANNED_STEPS_STR, UNPLANNED_STEPS_STR, GOAL_STR});
        // colors for the chart legend
        set.setColors(Color.parseColor(PASTEL_GREEN), Color.parseColor(PASTEL_BLUE),
                      Color.parseColor(LIGHT_GREY));

        BarData data = new BarData(set);
        return data;
    }

    /**
     *
     * @param label label of the thing you are updating
     * @param dates list of dates that will be the new
     * @param list
     */
    public void onDataRetrieved(String label, List<String> dates, List<Integer> list) {
        Log.i("SHIT", "progress chart has been notified");
        update(label, dates, list);
    }

}

/**
 *
 */
class DateFormatter implements IAxisValueFormatter {
    private SimpleDateFormat simpleDateFormat;

    /**
     * ctor for DateFormatter
     */
    public DateFormatter() {
        simpleDateFormat = new SimpleDateFormat(MONTH_DAY_FMT);
    }

    /**
     *
     * @param value is the value in the axis to convert to a label
     * @param axis is the axis that you
     * @return
     */
    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        Calendar cal = Calendar.getInstance();
        int max = (int) axis.getAxisMaximum();
        if(value >= max-1 || value != (int)value) {
            return "";
        }
        cal.add(Calendar.DAY_OF_YEAR, -1*(max-(int)value-2));
        return simpleDateFormat.format(cal.getTime());
    }
}